# # See https://pre-commit.com for more information
# default_language_version:
#     python: python3.11
# # See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    - id: trailing-whitespace # trims trailing whitespace.
    - id: end-of-file-fixer # ensures that a file is either empty, or ends with one newline.
    - id: check-added-large-files # prevents giant files from being committed.
    - id: check-case-conflict # checks for files that would conflict in case-insensitive filesystems.
    - id: pretty-format-json # sets a standard for formatting json files.
    - id: check-ast # simply checks whether the files parse as valid python.
    - id: check-json # checks json files for parseable syntax.
    - id: check-xml # checks xml files for parseable syntax.
    - id: check-yaml # checks yaml files for parseable syntax.
    - id: detect-private-key # detects the presence of private keys.
    - id: name-tests-test # verifies that test files are named correctly.
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort # isort your imports, so you don't have to.
        name: isort (python)
        args: ["--profile", "black"]
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black #  Black: The uncompromising Python code formatter
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8 # a command-line utility for enforcing style consistency across Python projects.
        additional_dependencies:
          [
            "flake8-bugbear", # finding likely bugs and design problems in your program
            "flake8-comprehensions", # plugin that helps you write better list/set/dict comprehensions.
            "flake8-mutable",
            "flake8-print", # check for Print statements in python files.
            "flake8-simplify", # plugin that helps you simplify your code.
          ]
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.32.0
    hooks:
      - id: pyupgrade # automatically upgrade syntax for newer versions.
        args: ["--py36-plus", "--py37-plus", "--py38-plus", "--py39-plus", "--py310-plus", "--py311-plus"]
