# Generated by Django 4.1.3 on 2023-01-30 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0002_module_submodule"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModuleAttributes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("passing_score", models.DecimalField(decimal_places=2, max_digits=5)),
                ("xp_multiplier", models.DecimalField(decimal_places=2, max_digits=5)),
                ("expiry_date", models.DateTimeField()),
                ("xp_bonus", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module",
                        to="organizations.module",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_organization",
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModuleActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_on", models.DateTimeField()),
                ("attempt_num", models.PositiveIntegerField(default=1)),
                ("expiry_date", models.DateTimeField()),
                ("complete", models.BooleanField(default=False)),
                ("start_time", models.DateTimeField()),
                ("last_accessed", models.DateField()),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.moduleattributes",
                    ),
                ),
                (
                    "sub_module",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="organizations.submodule",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
