# Generated by Django 4.1.3 on 2023-01-30 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_moduleattributes_moduleactivity"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("duration", models.DurationField()),
                ("log_event", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.SmallIntegerField()),
                ("comments", models.TextField()),
                ("timestamp", models.DateTimeField()),
                (
                    "module_activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.moduleactivity",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("duration", models.DurationField()),
                ("score", models.DecimalField(decimal_places=2, max_digits=5)),
                ("earned_certificate", models.BooleanField(default=False)),
                ("rewarded_xp", models.BooleanField(default=False)),
                ("certificate_timestamp", models.DateTimeField()),
                ("attempts_count", models.PositiveIntegerField()),
                ("xp", models.IntegerField()),
                ("mistakes", models.JSONField(default=dict)),
                ("complete", models.BooleanField(default=False)),
                (
                    "module_activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.moduleactivity",
                    ),
                ),
            ],
        ),
    ]
