# Generated by Django 4.1.3 on 2023-01-31 09:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0004_useractivity_feedback_assessment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submodule",
            name="max_attempts",
        ),
        migrations.AddField(
            model_name="moduleattributes",
            name="max_attempts",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="moduleattributes",
            name="trainers",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
