# Generated by Django 4.1.3 on 2023-02-28 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0005_remove_submodule_max_attempts_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attempt_number", models.PositiveIntegerField()),
                ("mistakes", models.JSONField(default=dict)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("order", models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("level", models.PositiveSmallIntegerField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.category",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.module",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LevelActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("complete", models.BooleanField(default=False)),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.level",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="submodule",
            name="module",
        ),
        migrations.RemoveField(
            model_name="moduleactivity",
            name="attempt_num",
        ),
        migrations.RemoveField(
            model_name="moduleactivity",
            name="expiry_date",
        ),
        migrations.RemoveField(
            model_name="moduleactivity",
            name="start_time",
        ),
        migrations.RemoveField(
            model_name="moduleactivity",
            name="sub_module",
        ),
        migrations.DeleteModel(
            name="Assessment",
        ),
        migrations.DeleteModel(
            name="SubModule",
        ),
        migrations.AddField(
            model_name="levelactivity",
            name="moduleActivity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.moduleactivity",
            ),
        ),
        migrations.AddField(
            model_name="attempt",
            name="level_activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.levelactivity",
            ),
        ),
    ]
