# Generated by Django 4.1.3 on 2023-03-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0006_attempt_category_level_levelactivity_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="moduleattributes",
            name="trainers",
        ),
        migrations.AlterField(
            model_name="moduleattributes",
            name="expiry_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="moduleattributes",
            name="max_attempts",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="moduleattributes",
            name="passing_score",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name="moduleattributes",
            name="xp_bonus",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name="moduleattributes",
            name="xp_multiplier",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
