# Generated by Django 4.1.3 on 2023-03-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0007_remove_moduleattributes_trainers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moduleattributes",
            name="expiry_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="moduleattributes",
            name="max_attempts",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="moduleattributes",
            name="passing_score",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="moduleattributes",
            name="xp_bonus",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="moduleattributes",
            name="xp_multiplier",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
