# Generated by Django 4.1.3 on 2023-03-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0008_alter_moduleattributes_expiry_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="moduleactivity",
            name="last_accessed",
        ),
        migrations.AddField(
            model_name="moduleactivity",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
