# Generated by Django 4.1.3 on 2023-03-17 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0011_organization_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attempt",
            old_name="mistakes",
            new_name="data",
        ),
        migrations.AddField(
            model_name="attempt",
            name="duration",
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
