# Generated by Django 4.1.3 on 2023-03-24 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0012_rename_mistakes_attempt_data_attempt_duration"),
    ]

    operations = [
        migrations.RenameField(
            model_name="levelactivity",
            old_name="moduleActivity",
            new_name="module_activity",
        ),
    ]
