# Generated by Django 4.1.3 on 2023-03-29 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0013_rename_moduleactivity_levelactivity_module_activity"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="levelactivity",
            options={"verbose_name_plural": "Level Activities"},
        ),
        migrations.AlterModelOptions(
            name="moduleactivity",
            options={"verbose_name_plural": "Module Activities"},
        ),
        migrations.AlterModelOptions(
            name="moduleattributes",
            options={"verbose_name_plural": "Module Attributes"},
        ),
        migrations.AddField(
            model_name="moduleactivity",
            name="complete_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="moduleactivity",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="model_attributes",
                to="organizations.moduleattributes",
            ),
        ),
    ]
