# Generated by Django 4.1.3 on 2023-04-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0016_useractivity_module_useractivity_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="useractivity",
            options={"verbose_name_plural": "User Activities"},
        ),
        migrations.AddField(
            model_name="moduleactivity",
            name="pass_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
