# Generated by Django 4.1.3 on 2023-05-05 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0017_alter_useractivity_options_moduleactivity_pass_date"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="attempt",
            unique_together={("level_activity", "attempt_number")},
        ),
    ]
