# Generated by Django 4.1.3 on 2023-05-26 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0018_alter_attempt_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="useractivity",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2023, 5, 26, 21, 12, 40, 639186),
            ),
            preserve_default=False,
        ),
    ]
