# Generated by Django 4.1.3 on 2023-05-26 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0019_useractivity_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="attempt",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2023, 5, 26, 23, 9, 40, 171668),
            ),
            preserve_default=False,
        ),
    ]
