# Generated by Django 4.1.3 on 2023-05-26 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0020_attempt_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="moduleattributes",
            name="xp_bonus",
        ),
        migrations.RemoveField(
            model_name="moduleattributes",
            name="xp_multiplier",
        ),
    ]
