# Generated by Django 4.1.3 on 2023-06-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0021_remove_moduleattributes_xp_bonus_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="levelactivity",
            name="complete",
            field=models.BooleanField(default=True),
        ),
    ]
