# Generated by Django 4.1.3 on 2023-11-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0022_alter_levelactivity_complete"),
    ]

    operations = [
        migrations.AddField(
            model_name="moduleattributes",
            name="ideal_mistake",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
