# Generated by Django 4.1.3 on 2023-12-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0024_moduleattributes_mistakes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moduleattributes",
            name="mistakes",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
