# Generated by Django 4.1.3 on 2023-01-31 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_rename_staff_user_deleted_user_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="staff",
            field=models.BooleanField(default=False),
        ),
    ]
