# Generated by Django 4.1.3 on 2023-02-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_user_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("organization admin", "Organization Admin"),
                    ("orgnization learner", "Organization Learner"),
                    ("organization trainer", "Organization Trainer"),
                    ("cusmat", "Cusmat"),
                ],
                help_text="Organization User Type",
                max_length=64,
                null=True,
                verbose_name="User Type",
            ),
        ),
    ]
