# Generated by Django 4.1.3 on 2023-02-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0005_remove_submodule_max_attempts_and_more"),
        ("accounts", "0008_alter_user_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="access_type",
            field=models.CharField(
                choices=[
                    ("Admin", "Admin"),
                    ("Learner", "Learner"),
                    ("Trainer", "Trainer"),
                ],
                default="Learner",
                help_text="Organization User Type",
                max_length=64,
                verbose_name="User Type",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_filter",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="user_id",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="department",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="designation",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="employee_code",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="grade",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="region",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="work_location",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="zone",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="user",
            unique_together={("organization", "employee_code")},
        ),
        migrations.RemoveField(
            model_name="user",
            name="contact",
        ),
        migrations.RemoveField(
            model_name="user",
            name="email",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_type",
        ),
    ]
