# Generated by Django 4.1.3 on 2023-03-14 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="access_type",
            field=models.CharField(
                choices=[
                    ("Admin", "Admin"),
                    ("Learner", "Learner"),
                    ("Trainer", "Trainer"),
                    ("Cusmat", "Cusmat"),
                ],
                default="Learner",
                help_text="Organization User Type",
                max_length=64,
                verbose_name="User Type",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="region",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="zone",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
