# Generated by Django 4.1.3 on 2023-03-15 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_passwordresettoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresettoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 15, 14, 7, 25, 814694, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
