# Generated by Django 4.1.3 on 2023-03-17 06:54

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_alter_passwordresettoken_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresettoken",
            name="expires_at",
            field=models.DateTimeField(default=accounts.models.get_default_my_date),
        ),
        migrations.AlterField(
            model_name="user",
            name="employee_code",
            field=models.CharField(max_length=100),
        ),
    ]
