# Generated by Django 4.1.3 on 2023-03-27 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_alter_passwordresettoken_expires_at_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OTP",
        ),
    ]
