# Generated by Django 4.1.3 on 2023-03-29 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_alter_passwordresettoken_expires_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="region",
        ),
        migrations.RemoveField(
            model_name="user",
            name="zone",
        ),
    ]
