# Generated by Django 4.1.3 on 2023-03-31 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_delete_otp"),
        ("accounts", "0015_remove_user_region_remove_user_zone"),
    ]

    operations = []
