# Generated by Django 4.1.3 on 2023-05-07 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0018_alter_attempt_unique_together"),
        ("accounts", "0016_merge_20230331_1527"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="user",
            unique_together={("organization", "user_id")},
        ),
    ]
