# Generated by Django 4.1.3 on 2023-05-17 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0018_alter_attempt_unique_together"),
        ("accounts", "0017_alter_user_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="user",
            unique_together={
                ("organization", "user_id"),
                ("organization", "employee_code"),
            },
        ),
    ]
