# Generated by Django 4.1.3 on 2023-06-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0021_user_age_user_batch_user_city_user_course_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female")],
                default="Male",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.CharField(
                help_text="Will be treated as mobile no. for Immertive Organization",
                max_length=100,
            ),
        ),
    ]
